core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pages.urls")),
    path("tasks/", include("tasks.urls")),
]

pages/urls.py
from django.urls import path
from . import views

app_name = "pages"

urlpatterns = [
    path("", views.home, name="home"),
]

tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"

urlpatterns = [
    path("", views.index, name="index"),
    path("add/", views.add, name="add"),
    path("<int:id>/detail/", views.detail, name="detail"),
    path("<int:id>/edit/", views.edit, name="edit"),
    path("<int:id>/delete/", views.delete, name="delete"),
]

tasks/models.py
from django.db import models


class Task(models.Model):
    title = models.CharField(max_length=100, verbose_name="待辦事項")
    description = models.TextField(blank=True, null=True, verbose_name="內容")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="創建時間")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="更新時間")
    is_deleted = models.BooleanField(default=False, verbose_name="已刪除")

    def __str__(self) -> str:
        return self.title

pages/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse


def home(request: HttpRequest) -> HttpResponse:
    return render(request, "pages/home.html")

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpRequest
from tasks.models import Task
from django.contrib import messages


def index(request: HttpRequest) -> HttpResponse:
    # tasks = Task.objects.all()
    tasks = Task.objects.filter(is_deleted=False)

    context = {"tasks": tasks}

    return render(request, "tasks/index.html", context)


def add(request: HttpRequest) -> HttpResponse:
    if request.POST:
        task = Task()
        task.title = request.POST.get("title")
        task.description = request.POST.get("description")
        task.save()

        messages.success(request, "創建成功")

        # 繼續待在新增頁面，可以進行下一筆任務新增
        return redirect("tasks:add")

    return render(request, "tasks/add.html")


def detail(request: HttpRequest, id: int) -> HttpResponse:
    task = get_object_or_404(Task, id=id)
    context = {"task": task}

    return render(request, "tasks/detail.html", context)


def edit(request: HttpRequest, id: int) -> HttpResponse:
    task = get_object_or_404(Task, id=id)
    context = {"task": task}

    if request.POST:
        task.title = request.POST.get("title", task.title)
        task.description = request.POST.get("description", task.description)
        task.save()

        messages.success(request, "更新成功")
        return redirect("tasks:detail", id=task.id)

    return render(request, "tasks/edit.html", context)


def delete(request: HttpRequest, id: int) -> HttpResponse:
    if request.POST:
        task = get_object_or_404(Task, id=id)

        task.is_deleted = True
        task.save()
        # task.delete()

        messages.success(request, "軟刪除成功")

        return redirect("tasks:index")

templates/pages/home.html
{% extends "shared/base.html" %}

{% block title %}
Home
{% endblock title %}

{% block content %}
<h1>Home page</h1>
<a href="{% url 'tasks:index' %}">任務功能</a>
{% endblock content %}

templates/pages/index.html
{% extends "shared/base.html" %}

{% block title %}
Index
{% endblock title %}

{% block content %}
<h1>Index page</h1>
{% endblock content %}

templates/shared/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% block content %}{% endblock content %}
		{% include "shared/footer.html" %}
  </body>
</html>

templates/shared/footer.html
<footer>
  <div style="font-size: 10px; color: red">django-crud-template</div>
</footer>

templates/tasks/add.html
{% extends "shared/base.html" %}

{% block content %}
<a href="{% url "tasks:index" %}">回到任務列表</a>
<h1>新增任務</h1>
<form method="POST" action="">
	{% csrf_token %}

	<div>
		<label for="title">待辦事項</label>
		<input name="title" type="text" id="title">
	</div>

	<div>
		<label for="description">內容</label>
		<textarea name="description" id="description"></textarea>
	</div>

	<button>創建</button>
</form>
{% endblock content %}

templates/tasks/detail.html
{% extends "shared/base.html" %}

{% block title %}任務細節{% endblock title %}


{% block content %}
<a href="{% url "tasks:index" %}">回到任務列表</a>
<h1>任務細節</h1>

<h2>待辦事項</h2>
<div>{{ task.title }}</div>

<h2>內容</h2>
{% if task.description %}
<div>{{ task.description }}</div>
{% endif %}
<a href="{% url "tasks:edit" task.id %}">修改待辦事項</a>

{% endblock content %}

templates/tasks/edit.html
{% extends "shared/base.html" %}

{% block content %}
<a href="{% url "tasks:index" %}">回到任務列表</a>
<h1>修改任務</h1>
<form method="POST">
	{% csrf_token %}

	<div>
		<label for="title">待辦事項</label>
		<input name="title" type="text" id="title" value={{ task.title }}>
	</div>

	<div>
		<label for="description">內容</label>
		<textarea name="description" id="description">{{ task.description }}</textarea>
	</div>

	<button>更新</button>
</form>
{% endblock content %}

templates/tasks/index.html
{% extends "shared/base.html" %}

{% block title %}任務列表{% endblock title %}


{% block content %}

<a href="{% url "pages:home" %}">回首頁</a>
<h1>任務列表</h1>
<a href="{% url 'tasks:add' %}">新增任務</a>

<ul>
	{% for task in tasks %}
	<li>
		<a href="{% url "tasks:detail" task.id %}">{{ task }}</a> 
		<form method="post" action="{% url "tasks:delete" task.id %}">
			{% csrf_token %}
			<button>軟刪除</button>
		</form>
	</li>
	{% endfor %}
</ul>

{% endblock content %}